### ISSUE TITLE
Yarn executable was not detected in the system

### ISSUE THREAD

**Issue by afomi** [pivotal-cf/cfdev#9]
![err](https://user-images.githubusercontent.com/67984/36821146-62fb1d14-1ca6-11e8-909a-eebfa05c720c.png)

It took quite a while, but, I was able to get CF running locally! 😄 
On pushing a vanilla Rails app, I got the yarn failure above.

Where do I go from here? 

I can push the same app to PWS. Where is yarn handled there? Where do I specify it here?

Thanks,

**Comment by sclevine** [comment]
Hi @afomi,

Thank you for trying out our first alpha release! Sorry that you're running into this issue.

Could you provide the full output of `cf push` on both PCF Dev and PWS?

Could you also confirm that both apps have the same memory and disk quotas?

Unless the app is running out of memory or disk space during staging, the error you're encountering is likely due to a difference in buildpack version.

**Comment by afomi** [comment]
@sclevine, I haven't resolved it, but I've been able to move forward.

1) I updated `manifest.yml` by specifying a recent buildpack as follows:

```
---
  applications:
  - name: stories
    command: bundle exec rake db:migrate && bundle exec rails s -p $PORT
    memory: 1024M
    buildpack: https://github.com/cloudfoundry/ruby-buildpack#v1.7.14 .   
```

2) I had to get a database (PostgreSQL) running in a Docker container, and have my app connect to it from within PCF. (Still not there, but on my way)

Thanks for your assistance offline!
